services:
  container:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: vlasolver
    platform: linux/amd64
    volumes:
      - ..:/workspace/vlasolver
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ~/.config/nvim:/home/ubuntu/.config/nvim:ro
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
    environment:
      - DISPLAY=$DISPLAY
    working_dir: /workspace/vlasolver
    tty: true
    stdin_open: true
