[grid]
nx = 128
ny = 128
nvx = 64
nvy = 64
ngc = 3

[grid_electron]
x_min = -1.0
Lx = 2.0
y_min = -1.0
Ly = 2.0
; normalized to electron thermal velocity
vx_min = -5.0
Lvx = 20.0
vy_min = -7.0
Lvy = 14.0

[grid_ion]
x_min = -1.0
Lx = 2.0
y_min = -1.0
Ly = 2.0
; normalized to ion thermal velocity
vx_min = -5.0
Lvx = 20.0
vy_min = -7.0
Lvy = 14.0

[world]
dt = 5.0e-4
total_time = 5e-1
total_steps = 1000
diag_steps = 10

[output]
folder = data/sheath_cylinder
prefix = output
