[grid]
nx = 128
ny = 128
nvx = 64
nvy = 64
ngc = 3

[grid_electron]
x_min = -10.0
Lx = 20.0
y_min = -10.0
Ly = 20.0
; normalized to electron thermal velocity
vx_min = -10.0
Lvx = 20.0
vy_min = -10.0
Lvy = 20.0

[grid_ion]
x_min = -10.0
Lx = 20.0
y_min = -10.0
Ly = 20.0
; normalized to ion thermal velocity
vx_min = -5.0
Lvx = 10.0
vy_min = -5.0
Lvy = 10.0

[world]
dt = 5.0e-2
total_time = 200
total_steps = 4000
diag_steps = 40

[output]
folder = data/sheath_cylinder
prefix = output
