[grid]
nx = 128
ny = 128
nvx = 64
nvy = 64
ngc = 3

[grid_electron]
x_min = -10.0
Lx = 20.0
y_min = -10.0
Ly = 20.0
; normalized to electron thermal velocity
vx_min = -6.0
Lvx = 12.0
vy_min = -6.0
Lvy = 12.0

[grid_ion]
x_min = -10.0
Lx = 20.0
y_min = -10.0
Ly = 20.0
; normalized to ion thermal velocity
vx_min = -6.0
Lvx = 12.0
vy_min = -6.0
Lvy = 12.0

[world]
dt = 5.0e-2
total_time = 600
total_steps = 12000
diag_steps = 120

[output]
folder = data/sheath_cylinder
prefix = output
