"""
Generate hardcoded M, N, d evaluators from derivation_case3.ju.py and
derivation_case4.ju.py. Run this script once to produce the formulas module,
then poisson.py no longer needs sympy at runtime.

Generates per-element lambda functions (M[i][j], d[i], N[i][offset]) for
each sub-case and eta sign, because each row uses different per-interface
normals, jumps, and betas.
"""

import contextlib
import importlib.util
import io
import os
import re

import sympy as sp

_HERE = os.path.dirname(os.path.abspath(__file__))


def _load_derivation(filename, name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(_HERE, filename))
    mod = importlib.util.module_from_spec(spec)
    with contextlib.redirect_stdout(io.StringIO()):
        spec.loader.exec_module(mod)
    return mod


d3 = _load_derivation("derivation_case3.ju.py", "_d3_deriv")
d4 = _load_derivation("derivation_case4.ju.py", "_d4_deriv")

# Map original sympy symbols → Python-friendly symbols
_ARG_NAMES = [
    "theta_R",
    "theta_T",
    "theta_L",
    "theta_B",
    "theta_r",
    "theta_t",
    "theta_l",
    "theta_b",
    "nx",
    "ny",
    "a_val",
    "b_val",
    "a_tau_val",
    "bp",
    "bm",
    "bj",
    "dx",
    "dy",
]
_PY_SYMS = [sp.Symbol(n) for n in _ARG_NAMES]

_ORIG_SYMS = [
    d3.theta_R,
    d3.theta_T,
    d3.theta_L,
    d3.theta_B,
    d3.theta_r,
    d3.theta_t,
    d3.theta_l,
    d3.theta_b,
    d3.nx,
    d3.ny,
    d3.a,
    d3.b,
    d3.a_tau,
    d3.beta_p,
    d3.beta_m,
    d3.beta_jump,
    d3.dx,
    d3.dy,
]

_SYM_MAP = dict(zip(_ORIG_SYMS, _PY_SYMS))

_U_RE = re.compile(r"^u_\{i([+-]\d+),j([+-]\d+)\}$")
_ARGLIST = ", ".join(_ARG_NAMES)


def expr_to_code(expr):
    expr_subbed = expr.subs(_SYM_MAP)
    return sp.printing.lambdarepr.lambdarepr(expr_subbed)


def fmt_offset(di, dj):
    return f"({di:+d}, {dj:+d})"


def generate_eval_data(M_sym, Nu_sym, d_sym):
    """Extract per-element code strings from symbolic matrices.

    Returns:
        M_codes: [[str]] 3x3
        d_codes: [str] length 3
        N_codes: [{offset: str}] list of 3 dicts
        all_offsets: sorted list of (di,dj) tuples
    """
    M_codes = [["0.0"] * 3 for _ in range(3)]
    d_codes = ["0.0"] * 3
    N_codes = [{} for _ in range(3)]

    for i in range(3):
        for j in range(3):
            M_codes[i][j] = expr_to_code(M_sym[i, j])
        d_codes[i] = expr_to_code(d_sym[i])
        for sym in Nu_sym[i].free_symbols:
            m = _U_RE.match(str(sym))
            if not m:
                continue
            di, dj = int(m.group(1)), int(m.group(2))
            coef = Nu_sym[i].coeff(sym)
            N_codes[i][(di, dj)] = expr_to_code(coef)

    all_offsets = sorted(set().union(*(nc.keys() for nc in N_codes)))
    return M_codes, d_codes, N_codes, all_offsets


def generate_module():
    lines = []
    lines.append('"""Hardcoded M, N, d formulas for case 3 and case 4.')
    lines.append("Generated by generate_hardcoded_formulas.py — DO NOT EDIT.")
    lines.append('"""')
    lines.append("import numpy as np")
    lines.append("")

    # Collect all data
    all_data = {}  # key: (case_name, sub_case, eta_sign)

    case3_row_ifaces = {
        1: ("R", "extra", "T"),
        2: ("R", "T", "extra"),
        3: ("T", "L", "extra"),
        4: ("T", "L", "extra"),
        5: ("L", "B", "extra"),
        6: ("L", "B", "extra"),
        7: ("B", "R", "extra"),
        8: ("B", "R", "extra"),
    }

    for sub_case in range(1, 9):
        for eta_sign in (-1, +1):
            pts_neg = getattr(d3, f"s{sub_case}_pts_neg")
            pts = pts_neg if eta_sign < 0 else d3.points_for_eta_pos(pts_neg)
            with contextlib.redirect_stdout(io.StringIO()):
                M, Nu, d = d3.coeff_case3(eta_sign, pts)
            M_codes, d_codes, N_codes, all_offsets = generate_eval_data(M, Nu, d)
            all_data[("case3", sub_case, eta_sign)] = {
                "M": M_codes,
                "d": d_codes,
                "N": N_codes,
                "offsets": all_offsets,
                "row_ifaces": case3_row_ifaces[sub_case],
            }

    case4_row_ifaces = {
        1: ("R", "T", "L"),
        2: ("R", "T", "B"),
        3: ("R", "B", "L"),
        4: ("T", "B", "L"),
    }

    for sub_case in range(1, 5):
        for eta_sign in (-1, +1):
            pts_neg = getattr(d4, f"s{sub_case}_pts_neg")
            pts = pts_neg if eta_sign < 0 else d4.points_for_eta_pos(pts_neg)
            with contextlib.redirect_stdout(io.StringIO()):
                M, Nu, d = d4.coeff_case4(eta_sign, pts)
            M_codes, d_codes, N_codes, all_offsets = generate_eval_data(M, Nu, d)
            all_data[("case4", sub_case, eta_sign)] = {
                "M": M_codes,
                "d": d_codes,
                "N": N_codes,
                "offsets": all_offsets,
                "row_ifaces": case4_row_ifaces[sub_case],
            }

    # Generate per-element lambda functions
    lines.append("# Per-element evaluator functions")
    lines.append("# Each function takes 17 arguments and returns a scalar.")
    lines.append("")

    for (case_name, sub_case, eta_sign), data in sorted(all_data.items()):
        eta_tag = "m1" if eta_sign < 0 else "p1"
        prefix = f"{case_name}_sc{sub_case}_eta_{eta_tag}"

        # M[i][j] lambdas
        for i in range(3):
            for j in range(3):
                code = data["M"][i][j]
                fname = f"M_{prefix}_r{i}c{j}"
                lines.append(f"def {fname}({_ARGLIST}):")
                lines.append(f"    return {code}")
                lines.append("")

        # d[i] lambdas
        for i in range(3):
            code = data["d"][i]
            fname = f"d_{prefix}_r{i}"
            lines.append(f"def {fname}({_ARGLIST}):")
            lines.append(f"    return {code}")
            lines.append("")

        # N[i][offset] lambdas
        for i in range(3):
            for (di, dj), code in sorted(data["N"][i].items()):
                off_tag = f"o{di:+d}_{dj:+d}".replace("+", "p").replace("-", "m")
                fname = f"N_{prefix}_r{i}_{off_tag}"
                lines.append(f"def {fname}({_ARGLIST}):")
                lines.append(f"    return {code}")
                lines.append("")

    # Generate evaluator dispatch data structures
    lines.append("")
    lines.append("# Evaluator dispatch tables")
    lines.append("# Each entry maps to a dict with:")
    lines.append("#   'M': [[func]] 3x3, 'd': [func], 'N': [[{offset: func}]] 3-list,")
    lines.append("#   'offsets': [(di,dj)], 'row_ifaces': (str, str, str)")
    lines.append("")

    # We need to build these as actual Python data structures. Use a helper
    # function that takes function references.
    lines.append("CASE3_EVAL = {}")
    lines.append("CASE4_EVAL = {}")
    lines.append("")

    for (case_name, sub_case, eta_sign), data in sorted(all_data.items()):
        eta_tag = "m1" if eta_sign < 0 else "p1"
        prefix = f"{case_name}_sc{sub_case}_eta_{eta_tag}"
        tbl = "CASE3_EVAL" if case_name == "case3" else "CASE4_EVAL"

        lines.append(f"# {case_name} sub-case {sub_case}, eta sign {eta_sign:+d}")
        lines.append(f"_{prefix}_M = [")
        for i in range(3):
            fnames = [f"M_{prefix}_r{i}c{j}" for j in range(3)]
            lines.append(f"    [{', '.join(fnames)}],")
        lines.append(f"]")
        lines.append(
            f"_{prefix}_d = [{', '.join(f'd_{prefix}_r{i}' for i in range(3))}]"
        )
        lines.append(f"_{prefix}_N = [")
        for i in range(3):
            items = []
            for di, dj in sorted(data["N"][i].keys()):
                off_tag = f"o{di:+d}_{dj:+d}".replace("+", "p").replace("-", "m")
                items.append(f"{fmt_offset(di, dj)}: N_{prefix}_r{i}_{off_tag}")
            lines.append(f"    {{{', '.join(items)}}},")
        lines.append(f"]")
        offsets_str = ", ".join(fmt_offset(di, dj) for di, dj in data["offsets"])
        ifaces = ", ".join(f'"{x}"' for x in data["row_ifaces"])
        lines.append(f"_{prefix}_offsets = [{offsets_str}]")
        lines.append(f"_{prefix}_row_ifaces = ({ifaces})")
        lines.append(f"_{prefix} = {{")
        lines.append(f"    'M': _{prefix}_M, 'd': _{prefix}_d, 'N': _{prefix}_N,")
        lines.append(
            f"    'offsets': _{prefix}_offsets, 'row_ifaces': _{prefix}_row_ifaces,"
        )
        lines.append(f"}}")
        lines.append(f"{tbl}[({sub_case}, {eta_sign})] = _{prefix}")
        lines.append("")

    return "\n".join(lines)


output_path = os.path.join(_HERE, "_hardcoded_formulas.py")
code = generate_module()
with open(output_path, "w") as f:
    f.write(code)

print(f"Generated {output_path}")
