[grid]
nx = 50
ny = 100
nvx = 50
nvy = 50
ngc = 3


[grid_electron]
x_min = 0.0
Lx = 20.0
y_min = 0.0
Ly = 20.0
; normalized to electron thermal velocity
vx_min = -4.0
Lvx = 8.0
vy_min = -5.0
Lvy = 10.0

[grid_ion]
x_min = 0.0
Lx = 20.0
y_min = 0.0
Ly = 20.0
; normalized to ion thermal velocity
vx_min = -4.0
Lvx = 8.0
vy_min = -15.0
Lvy = 16.0

[world]
; dt = 1.5e-2
; total_time = 120.0
; total_steps = 8000
; diag_steps = 80
dt = 5.0e-2
total_time = 1000.0
total_steps = 20000
diag_steps = 200

[output]
folder = data/sheath_rough_wall
prefix = output
