[grid]
nx = 10
ny = 125
nvx = 30
nvy = 110
ngc = 3

[grid_electron]
x_min = 0.0
Lx = 20.0
y_min = 0.0
Ly = 20.0
; normalized to electron thermal velocity
vx_min = -4.0
Lvx = 8.0
vy_min = -5.0
Lvy = 10.0

[grid_ion]
x_min = 0.0
Lx = 20.0
y_min = 0.0
Ly = 20.0
; normalized to ion thermal velocity
vx_min = -4.0
Lvx = 8.0
vy_min = -15.0
Lvy = 16.0

[world]
dt = 1.5e-2
total_time = 120.0
total_step = 8000
diag_step = 80

[output]
folder = data/sheath
prefix = output
